version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name kadai5-codedeploy --s3-location s3://kadai5-codeartifact-bucket-20241218/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src